<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="Politique de confidentialité" class="section">
        <div class="container">
            <div class="row align-items-center">
                <h1>Politique de confidentialité</h1>
                <h2>1. La protection des données en un coup d'œil</h2>
                <h4>Informations générales</h4> <p>Les indications suivantes donnent un aperçu simple de ce qui se passe avec vos données personnelles lorsque vous visitez notre site web. Les données personnelles sont toutes les données qui permettent de vous identifier personnellement. Vous trouverez des informations détaillées sur le thème de la protection des données dans notre déclaration de protection des données figurant dans ce texte.</p>
                <h4>Collecte de données sur ce site</h4> <h4>Qui est responsable de la collecte des données sur ce site ?</h4> <p>Le traitement des données sur ce site web est effectué par l'exploitant du site web. Vous trouverez les coordonnées de ce dernier dans la section "Impressum" du site</p> <h4>Comment collectons-nous vos données ?</h4> <p>Vos données sont collectées, d'une part, lorsque vous nous les contactez. Il peut s'agir, par exemple, de données que vous saisissez dans un formulaire de contact.</p> <p>D'autres données sont collectées automatiquement ou après votre accord par nos systèmes informatiques lorsque vous visitez le site web. Il s'agit principalement de données techniques (par exemple, le navigateur Internet, le système d'exploitation ou l'heure de consultation de la page). La saisie de ces données s'effectue automatiquement dès que vous accédez à ce site web.</p> <h4>Dans quel but utilisons-nous vos données ?</h4> <p>Une partie des données est collectée afin de garantir une mise à disposition sans erreurs du site web. D'autres données peuvent être utilisées pour analyser votre comportement sue le site.</p> <h4>Quels droits avez-vous concernant vos données ?</h4> <p>Vous avez à tout moment le droit d'obtenir gratuitement des informations sur l'origine, le destinataire et la finalité de vos données personnelles enregistrées. Vous avez également le droit d'exiger la rectification ou la suppression de ces données. Si vous avez donné votre consentement au traitement des données, vous pouvez à tout moment révoquer ce consentement dans le future. Vous avez également le droit de demander la limitation du traitement de vos données personnelles dans certaines circonstances. En outre, vous disposez d'un droit de recours auprès de l'autorité de surveillance.</p> <p>Vous pouvez nous contacter à tout moment à ce sujet ou pour toute autre question relative à la protection des données.</p>
                <h4>Outils d'analyse et outils tiers</h4> <p>Lors de la visite de ce site web, votre comportement de navigation peut être évalué statistiquement. Cela se fait principalement à l'aide de ce que l'on appelle des programmes d'analyse. Vous trouverez des informations détaillées sur ces programmes d'analyse dans la déclaration de protection des données suivante.
                </p> 
                <h2>2. Hébergement</h2>
                <h4>Hébergement externe</h4> <p>Ce site web est hébergé par un prestataire de services externe (hébergeur). Les données personnelles collectées sur ce site sont stockées sur les serveurs de l'hébergeur. Il peut s'agir notamment d'adresses IP, de demandes de contact, de métadonnées et de données de communication, de données contractuelles, de données de contact, de noms, de consultations du site web et d'autres données générées par un site web.
                </p> <p>L'utilisation de l'hébergeur a pour but l'exécution du contrat vis-à-vis de nos clients potentiels et existants (article 6, paragraphe 1, point b du RGPD) et dans l'intérêt d'une mise à disposition sûre, rapide et efficace de notre offre en ligne par un fournisseur professionnel (article 6, paragraphe 1, point f du RGPD). Si un consentement correspondant a été demandé, le traitement est effectué exclusivement sur la base de l'article 6, paragraphe 1, point a), du RGPD et de l'article 25, paragraphe 1, de la loi sur la protection des données (TTDSG), dans la mesure où le consentement inclut le stockage de cookies ou l'accès à des informations dans le terminal de l'utilisateur (par ex. Device-Fingerprinting) au sens de la TTDSG. Le consentement est révocable à tout moment.</p> <p>Notre hébergeur ne traitera vos données que dans la mesure où cela est nécessaire à l'exécution de ses obligations de prestation et suivra nos instructions en ce qui concerne ces données.
                </p> <p>Nous utilisons l'hébergeur suivant :
                </p>
                <p>HOSTINGER INTERNATIONAL LIMITED<br>
                61 Lordou Vironos st.<br>
                6023 Larnaca<br>
                République de Chypre</p>
                <h4>Traitement de commandes</h4> <p>Nous avons conclu un contrat de traitement des commandes (CTP) avec le fournisseur mentionné. Il s'agit d'un contrat prescrit par la législation sur la protection des données, qui garantit que celui-ci traite les données personnelles des visiteurs de notre site web uniquement selon nos instructions et dans le respect du RGPD.
                </p>
                <h2>3. Informations générales et informations obligatoires</h2>
                <h4>Protection des données</h4> <p>Les exploitants de ces pages prennent la protection de vos données personnelles très au sérieux. Nous traitons vos données personnelles de manière confidentielle et conformément aux dispositions légales en matière de protection des données ainsi qu'à la présente déclaration de protection des données.</p> <p>Lorsque vous utilisez ce site web, diverses données personnelles sont collectées. Les données personnelles sont des données qui permettent de vous identifier personnellement. La présente déclaration de confidentialité explique quelles données nous collectons et à quelles fins nous les utilisons. Elle explique également comment et dans quel but nous le faisons.</p> <p>Nous attirons votre attention sur le fait que la transmission de données sur Internet (par ex. lors de la communication par e-mail) peut présenter des erreurs de sécurité. Une protection complète des données contre l'accès par des tiers n'est pas possible.</p>
                <h4>Remarque sur la personne responsable</h4> <p>Le responsable du traitement des données sur ce site Web est:</p> <p>Omar Zirite<br>
                Busso-Peus-Straße, 14<br>
                Wgh B20<br>
                48149 Münster</p>

                <p>Telefon: +49 17621461644<br>
                E-Mail: contact@marolet.ma</p>
                <p>Le responsable du traitement est la personne physique ou morale qui, seule ou conjointement avec d'autres, détermine les finalités et les moyens du traitement des données à caractère personnel (par exemple, les noms, les adresses électroniques ou autres).</p>

                <h4>Durée de stockage</h4> <p>Dans la mesure où aucune durée de stockage spécifique n'a été mentionnée dans la présente déclaration de protection des données, vos données à caractère personnel restent chez nous jusqu'à ce que la finalité du traitement des données n'ait plus lieu d'être. Si vous faites valoir une demande légitime d'effacement ou si vous révoquez votre consentement au traitement des données, vos données seront effacées, à moins que nous n'ayons d'autres raisons légalement valables de conserver vos données personnelles (par ex. délais de conservation en vertu du droit fiscal ou commercial) ; dans ce dernier cas, l'effacement aura lieu après la disparition de ces raisons.</p>
                <h4>Informations générales sur les bases juridiques du traitement des données sur ce site web</h4> <p>Si vous avez donné votre consentement au traitement des données, nous traitons vos données personnelles sur la base de l'article 6, paragraphe 1, point a) du RGPD ou de l'article 9, paragraphe 2, point a) du RGPD, dans la mesure où des catégories particulières de données sont traitées conformément à l'article 9, paragraphe 1 du RGPD. En cas de consentement explicite au transfert de données à caractère personnel vers des pays tiers, le traitement des données s'effectue en outre sur la base de l'article 49, paragraphe 1, point a) du RGPD. Si vous avez consenti à l'enregistrement de cookies ou à l'accès à des informations dans votre terminal (par exemple via l'empreinte digitale de l'appareil), le traitement des données s'effectue en outre sur la base de l'article 25, paragraphe 1, de la TTDSG. Ce consentement est révocable à tout moment. Si vos données sont nécessaires à l'exécution d'un contrat ou à la mise en œuvre de mesures précontractuelles, nous traitons vos données sur la base de l'article 6, paragraphe 1, point b), du RGPD. En outre, nous traitons vos données si elles sont nécessaires pour remplir une obligation légale sur la base de l'article 6, paragraphe 1, point c) du RGPD. Le traitement des données peut également être effectué sur la base de notre intérêt légitime conformément à l'article 6, paragraphe 1, point f), du RGPD. Les paragraphes suivants de la présente déclaration de protection des données informent sur les bases juridiques applicables dans chaque cas.</p>
                <h4>Révocation de votre consentement au traitement des données</h4> <p>De nombreuses opérations de traitement des données ne sont possibles qu'avec votre consentement explicite. Vous pouvez révoquer à tout moment un consentement déjà donné. La légalité du traitement des données effectué jusqu'à la révocation n'est pas affectée par la révocation.</p>
                <h4>Droit de s'opposer à la collecte de données dans des cas particuliers et à la publicité directe (art. 21 RGPD)</h4> <p>Si le traitement des données est effectué sur la base de l'article 6, paragraphe 1, point E ou f du RGPD, vous avez le droit de vous opposer à tout moment, pour des raisons tenant à votre situation particulière, au traitement de vos données personnelles ; ceci s'applique également à un profilage basé sur ces dispositions. Vous trouverez dans la présente déclaration de protection des données les bases juridiques respectives sur lesquelles repose un traitement. Si vous vous y opposez, nous ne traiterons plus vos données personnelles concernées, à moins que nous puissions démontrer des raisons impérieuses et dignes de protection pour le traitement qui prévalent sur vos intérêts, vos droits et vos libertés, ou que le traitement serve à faire valoir, à exercer ou à défendre des droits juridiques (opposition à l'art. 21, al. 1, du RGPD).</p> <p>Si vos données personnelles sont traitées à des fins de publicité directe, vous avez le droit de vous opposer à tout moment au traitement des données personnelles vous concernant à des fins de publicité directe, y compris au profilage dans la mesure où il est lié à cette publicité directe. Si vous vous y opposez, vos données personnelles ne seront plus utilisées à des fins de prospection directe (opposition conformément à l'art. 21 al. 2 dsgvo).</p>
                <h4>Droit de recours auprès de l'autorité de surveillance.</h4> <p>En cas de violation du RGPD, les personnes concernées disposent d'un droit de recours auprès d'une autorité de contrôle, notamment dans l'État membre de leur résidence habituelle, de leur lieu de travail ou du lieu de la violation présumée. Ce droit de recours s'exerce sans préjudice des autres voies de recours administratives ou judiciaires.</p>
                <h4>Droit à la portabilité des données</h4> <p>Vous avez le droit de vous faire un consentement ou de faire exécution à un tiers, dans un format courant et lisible par machine, les données que nous traitons de manière automatisée sur la base de votre consentement ou en exécution d'un contrat. Si vous demandez la transmission directe des données à un autre responsable, cela ne se fera que dans la mesure où cela est techniquement possible.</p>
                <h4>le cryptage SSL ou TLS</h4> <p>Pour des raisons de sécurité et afin de protéger la transmission de contenus confidentiels, comme par exemple les commandes ou les demandes que vous nous envoyez en tant qu'exploitant du site, ce site utilise un cryptage SSL ou TLS. Vous reconnaissez une connexion cryptée au fait que la ligne d'adresse du navigateur passe de "http://" à "https://" et au symbole du cadenas dans la ligne de votre navigateur.</p> <p>Si le cryptage SSL ou TLS est activé, les données que vous nous transmettez ne peuvent pas être lues par des tiers.</p>
                <h4>Accès, suppression et rectification</h4> <p>Dans le cadre des dispositions légales en vigueur, vous avez à tout moment le droit d'obtenir gratuitement des informations sur vos données personnelles enregistrées, leur origine et leur destinataire ainsi que sur la finalité du traitement des données et, le cas échéant, un droit de rectification ou de suppression de ces données. Pour cela, ainsi que pour toute autre question relative aux données personnelles, vous pouvez nous contacter à tout moment.</p>
                <h4>Droit à la limitation du traitement</h4> <p>Vous avez le droit de demander la limitation du traitement de vos données personnelles. Pour ce faire, vous pouvez nous contacter à tout moment. Le droit à la limitation du traitement existe dans les cas suivants :</p> <ul> <li>Si vous contestez l'exactitude de vos données à caractère personnel enregistrées chez nous, nous avons généralement besoin de temps pour le vérifier. Pendant la durée de la vérification, vous avez le droit d'exiger la limitation du traitement de vos données à caractère personnel.</li> <li>Si le traitement de vos données à caractère personnel s'est produit/se produit de manière illégale, vous pouvez demander la limitation du traitement des données au lieu de leur suppression.</li> <li>Si nous n'avons plus besoin de vos données à caractère personnel, mais que vous en avez besoin pour exercer, défendre ou faire valoir des droits juridiques, vous avez le droit de demander la limitation du traitement de vos données à caractère personnel au lieu de leur suppression.</li> <li>Si vous avez fait opposition conformément à l'article 21, paragraphe 1, du RGPD, une mise en balance de vos intérêts et des nôtres doit être effectuée. Tant qu'il n'a pas été déterminé quels intérêts prévalent, vous avez le droit de demander la limitation du traitement de vos données à caractère personnel.</li> </ul> <p>Si vous avez limité le traitement de vos données à caractère personnel, ces données ne peuvent être traitées - à l'exception de leur stockage - qu'avec votre consentement ou pour la constatation, l'exercice ou la défense de droits en justice ou pour la protection des droits d'une autre personne physique ou morale, ou encore pour un motif d'intérêt public important de l'Union européenne ou d'un État membre.</p>
                <h4>Newsletter et notifications par email</h4>
                <p>Marolet utilise le service Mailersend pour envoyer des courriels et des bulletins d'information. Mailersend est Mailersend, Inc. (228 Park Ave S, PMB 54955, New York, New York 10003-1502, US) "Mailersend". Mailersend fournit des services de courrier électronique transactionnel ("Services").</p>
                <p>Mailersend reçoit de Marolet pour l'envoi d'e-mails des données personnelles telles que le nom et le prénom ainsi que l'adresse e-mail de l'utilisateur. Les données sont stockées sur les serveurs de Mailersend Technologies aux États-Unis.
                </p>
                <p>Avec l'aide de Mailersend, Marolet peut analyser les campagnes des emails envoyées. Lorsqu'un utilisateur ouvre un e-mail envoyé avec Mailgun, un fichier contenu dans l'e-mail (appelé web beacon) se connecte aux serveurs de Mailersend aux États-Unis. De cette manière, il est possible de déterminer si un message de newsletter a été ouvert et quels liens ont été cliqués. Des informations techniques sont également enregistrées (par exemple, l'heure d'accès, l'adresse IP, le type de navigateur et le système d'exploitation). Ces informations ne peuvent pas être attribuées au destinataire respectif de la newsletter. Elles sont utilisées exclusivement pour l'analyse statistique des campagnes de newsletter. Les résultats de ces analyses peuvent être utilisés pour mieux adapter les futures newsletters aux intérêts des destinataires.
                </p>
                <p>Si les utilisateurs ne veulent pas d'une analyse par Mailersend, ils doivent se désinscrire de la newsletter. Nous fournissons un lien à cet effet dans chaque message de la newsletter. Cela n'affecte pas les données que nous avons stockées à d'autres fins (par exemple, les adresses e-mail pour l'espace membres).
                </p>
                <p>Le traitement des données a lieu sur la base de l'art. 6 Para. 1 Lettre b) du RGPD de l'UE pour les e-mails qui sont nécessaires à l'exécution du contrat et sur la base de l'art. 6 Para. 1 lettre a) du RGPD de l'UE pour les bulletins d'information auxquels l'utilisateur s'est abonné via opt-in sur Marolet.
                </p>
                <p>Les utilisateurs peuvent révoquer leur consentement à recevoir la newsletter à tout moment en se désinscrivant de la newsletter. L'utilisateur trouvera de plus amples informations sur la désinscription de la newsletter au point 4.1.1 de la présente déclaration de protection des données. La légalité des traitements de données déjà effectués n'est pas affectée par la révocation.
                </p>
                <p>Vous trouverez de plus amples informations dans la politique de confidentialité de Mailersend à l'adresse suivante : <a href="https://www.mailersend.com/legal/privacy-policy">https://www.mailersend.com/legal/privacy-policy</a>. 
                </p>
                <p>Marolet est autorisé à envoyer des newsletters et des offres que l'équipe de Marolet juge utiles pour l'utilisateur.
                </p>
                <h4>Accessibilité du contenu</h4>
                <p>Seuls les utilisateurs ont le contrôle de leur contenu, qu'ils souhaitent partager et mettre à la disposition des autres utilisateurs. Cela inclut tous les types de fichiers, de commentaires et de données personnelles. Marolet ne fournit que les conditions techniques et n'est pas responsable des actions des utilisateurs. Si un utilisateur décide de partager du matériel ou des informations provenant de tiers, il en est le seul responsable. La mesure dans laquelle les informations sont partagées sur Marolet n'est pas influencée par Marolet. Par conséquent, les utilisateurs sont les seuls à décider du contenu qu'ils rendent accessible.
                </p>
                <h2>4. Collecte de données sur ce site web</h2>
                <h4>Inscription par e-mail</h4> <p>Dans le cadre de l'enregistrement, les utilisateurs sont invités à fournir certaines informations personnelles. Marolet stocke les données suivantes sur les utilisateurs, qui sont saisies pendant le processus d'enregistrement.
                </p><p>- l'adresse électronique</p> <p>- Un mot de passe</p><p>- Nom et prénom </p><p>La base juridique de ce traitement des données à caractère personnel est l'article 6 (1) b) du règlement général sur la protection des données de l'UE (RGPD).</p>
                <h4>Cookies</h4> <p>Nos pages Internet utilisent ce que l'on appelle des "cookies". Les cookies sont de petits fichiers texte qui ne causent aucun dommage à votre terminal. Ils sont enregistrés sur votre terminal soit temporairement pour la durée d'une session (cookies de session), soit durablement (cookies permanents). Les cookies de session sont automatiquement supprimés à la fin de votre visite. Les cookies permanents restent enregistrés sur votre terminal jusqu'à ce que vous les supprimiez vous-même ou qu'une suppression automatique soit effectuée par votre navigateur web.</p> <p>Des cookies de sociétés tierces peuvent également être partiellement enregistrés sur votre terminal lorsque vous accédez à notre site (cookies tiers). Ceux-ci nous permettent ou vous permettent d'utiliser certains services de l'entreprise tierce (par exemple, les cookies pour le traitement des services de paiement).</p> <p>Les cookies ont différentes fonctions. De nombreux cookies sont techniquement nécessaires, car certaines fonctions du site web ne fonctionneraient pas sans eux (par exemple la fonction de panier d'achat ou l'affichage de vidéos). D'autres cookies servent à évaluer le comportement des utilisateurs ou à afficher des publicités.</p> <p>Les cookies nécessaires à l'exécution du processus de communication électronique, à la mise à disposition de certaines fonctions que vous souhaitez (par ex. pour la fonction de panier d'achat) ou à l'optimisation du site web (par ex. cookies de mesure d'audience web) (cookies nécessaires) sont enregistrés sur la base de l'article 6, paragraphe 1, point f du RGPD, sauf si une autre base juridique est indiquée. L'exploitant du site web a un intérêt légitime à l'enregistrement des cookies nécessaires pour une mise à disposition de ses services sans erreur technique et optimisée. Si un consentement a été demandé pour le stockage de cookies et de technologies de reconnaissance comparables, le traitement est effectué exclusivement sur la base de ce consentement (article 6, paragraphe 1, point a) du RGPD et article 25, paragraphe 1 de la TTDSG) ; le consentement peut être révoqué à tout moment.</p> <p>Vous pouvez configurer votre navigateur de manière à être informé de l'installation de cookies et à n'autoriser les cookies qu'au cas par cas, à exclure l'acceptation de cookies pour certains cas ou de manière générale, et à activer la suppression automatique des cookies à la fermeture du navigateur. En cas de désactivation des cookies, la fonctionnalité de ce site web peut être limitée.</p> <p>Si des cookies sont utilisés par des entreprises tierces ou à des fins d'analyse, nous vous en informerons séparément dans le cadre de la présente déclaration de protection des données et, le cas échéant, nous vous demanderons votre consentement.</p>
                <h4>Server-Log Dossiers</h4> <p>Le fournisseur des pages collecte et enregistre automatiquement des informations dans ce que l'on appelle des fichiers journaux du serveur, que votre navigateur nous transmet automatiquement. Il s'agit de ces informations :</p> <ul> <li>type et version du navigateur</li> <li>système d'exploitation utilisé</li> <li>URL de référence</li> <li>Nom d'hôte de l'ordinateur accédant au site</li> <li>Heure de la demande du serveur</li> <li>Adresse IP</li> </ul> <p>Ces données ne sont pas recoupées avec d'autres sources de données.</p> <p>La collecte de ces données s'effectue sur la base de l'article 6, paragraphe 1, point f du RGPD. L'exploitant du site web a un intérêt légitime à ce que son site web soit présenté sans erreur technique et à ce qu'il soit optimisé - pour cela, les fichiers journaux du serveur doivent être collectés.</p>
                <h4>Formulaire de contact</h4> <p>Si vous nous faites parvenir des demandes par le biais du formulaire de contact, les informations que vous avez fournies dans le formulaire de demande, y compris les données de contact que vous y avez indiquées, sont enregistrées chez nous à des fins de traitement de la demande et en cas de questions de suivi. Nous ne transmettons pas ces données sans votre consentement.</p> <p>Le traitement de ces données est basé sur l'article 6, paragraphe 1, point b), du RGPD, dans la mesure où votre demande est liée à l'exécution d'un contrat ou est nécessaire à l'exécution de mesures précontractuelles. Dans tous les autres cas, le traitement repose sur notre intérêt légitime à traiter efficacement les demandes qui nous sont adressées (article 6, paragraphe 1, point f) du RGPD) ou sur votre consentement (article 6, paragraphe 1, point a) du RGPD) dans la mesure où celui-ci a été demandé ; le consentement peut être retiré à tout moment.</p> <p>Les données que vous avez saisies dans le formulaire de contact restent chez nous jusqu'à ce que vous nous demandiez de les supprimer, que vous révoquiez votre consentement à leur enregistrement ou que la finalité de l'enregistrement des données devienne caduque (par ex. après le traitement de votre demande). Les dispositions légales contraignantes - en particulier les délais de conservation - ne sont pas affectées.</p>
                <h4>Demande par e-mail, téléphone ou fax</h4> <p>Si vous nous contactez par e-mail, téléphone ou fax, votre demande, y compris toutes les données personnelles qui en découlent (nom, demande), sera enregistrée et traitée par nos soins dans le but de traiter votre demande. Nous ne transmettons pas ces données sans votre consentement.</p> <p>Le traitement de ces données est basé sur l'article 6, paragraphe 1, point b) du RGPD, dans la mesure où votre demande est liée à l'exécution d'un contrat ou est nécessaire à l'exécution de mesures précontractuelles. Dans tous les autres cas, le traitement repose sur notre intérêt légitime à traiter efficacement les demandes qui nous sont adressées (article 6, paragraphe 1, point f) du RGPD) ou sur votre consentement (article 6, paragraphe 1, point a) du RGPD) dans la mesure où celui-ci a été demandé ; le consentement peut être retiré à tout moment.</p> <p>Les données que vous nous avez envoyées par le biais de demandes de contact restent chez nous jusqu'à ce que vous nous demandiez de les effacer, que vous révoquiez votre consentement à leur enregistrement ou que la finalité de l'enregistrement des données devienne caduque (par ex. après le traitement de votre demande). Les dispositions légales contraignantes - en particulier les délais de conservation légaux - ne sont pas affectées.</p>
                <h4>Demandes d'informations, suppression d'un compte</h4>
                <p>Les utilisateurs ont le droit de demander des informations sur les données stockées. En outre, les utilisateurs peuvent modifier, bloquer ou supprimer leurs données personnelles à tout moment. Vous pouvez envoyer une demande par courriel à contact@marolet.ma ou contacter Marolet par courrier. Les utilisateurs sont priés de fournir les informations suivantes dans les demandes écrites : nom, prénom, adresse électronique, adresse, identification au moyen d'une copie de la pièce d'identité (pièce d'identité valide).
                </p>
                <p>Pour des raisons techniques, après avoir été supprimées, les données personnelles peuvent encore être visibles pendant quelques jours. Marolet est tenu de garantir la disponibilité des données. Il est donc possible que les données supprimées restent dans le système de sauvegarde durant une période limitée. Toutefois, ces informations ne seront pas accessibles au public.
                </p>
                <p>Merci d'avoir lu notre politique de confidentialité ! Si vous avez des questions sur notre politique de confidentialité, vous pouvez nous envoyer un e-mail à tout moment à contact@marolet.ma.
                </p>
                <p>À bientôt sur Marolet et bonne chance dans vos études !
                </p>
                <h4>YouTube avec une confidentialité renforcée</h4>
                <p>Nous utilisons la plateforme YouTube.com pour publier nos propres vidéos et les rendre accessibles au public. YouTube est l'offre d'un tiers non lié à nous, à savoir YouTube LLC.
                </p>
                <p>Certaines pages Internet de notre offre contiennent des liens ou des connexions vers l'offre de YouTube. D'une manière générale, nous ne sommes pas responsables du contenu des pages Internet auxquelles renvoient ces liens. Si vous suivez un lien vers YouTube, nous attirons toutefois votre attention sur le fait que YouTube enregistre les données de ses utilisateurs (par ex. informations personnelles, adresse IP) conformément à sa propre politique d'utilisation des données et les utilise à des fins commerciales.
                </p>
                <p>Sur certaines de nos pages Internet, nous intégrons également directement des vidéos enregistrées sur YouTube. Lors de cette intégration, des contenus du site Internet de YouTube sont représentés dans des zones partielles d'une fenêtre de navigateur. Les vidéos YouTube ne sont toutefois appelées qu'après un clic séparé. Cette technique est également appelée "framing". Lorsque vous consultez une (sous-)page de notre offre Internet sur laquelle des vidéos YouTube sont intégrées sous cette forme, une connexion est établie avec les serveurs YouTube et le contenu est alors affiché sur la page Internet par le biais d'un message envoyé à votre navigateur.
                </p>
                <p>L'intégration de contenus YouTube s'effectue uniquement en "mode de protection des données étendu". YouTube met lui-même ce mode à disposition et garantit ainsi que YouTube ne stocke pas de cookies sur votre appareil. Lors de l'appel des pages concernées, l'adresse IP ainsi que les autres données mentionnées au point 4 sont toutefois transmises et indiquent ainsi en particulier lesquelles de nos pages Internet vous avez visitées. Cette information ne peut toutefois pas vous être attribuée, dans la mesure où vous ne vous êtes pas connecté à YouTube ou à un autre service Google (par ex. Google+) avant d'appeler la page ou que vous n'êtes pas connecté en permanence.
                </p>
                <p>
                Dès que vous démarrez la lecture d'une vidéo intégrée en cliquant dessus, YouTube n'enregistre sur votre appareil, grâce au mode de protection des données étendu, que des cookies qui ne contiennent pas de données personnelles identifiables, à moins que vous ne soyez actuellement connecté à un service Google. Ces cookies peuvent être empêchés par des paramètres et des extensions de navigateur appropriés.
                </p>
                <p>Adresse et lien vers la déclaration de confidentialité du fournisseur tiers :
                </p>
                <p>Google/YouTube : Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irlande - Déclaration de confidentialité : https://policies.google.com/privacy, Opt-Out : https://adssettings.google.com/authenticated, Privacy Shield : https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI.
                </p>
                <h4>Utilisation de Google Analytics</h4><br>
                <p>Nous utilisons Google Analytics pour analyser l'utilisation du site web. Les données ainsi obtenues sont utilisées pour optimiser notre site web ainsi que les mesures publicitaires.</p><br>
                <p>Google Analytics nous est fourni par Google Ireland Limited (Gordon House, Barrow Street, Dublin 4, Irlande). Google traite les données relatives à l'utilisation du site web en notre nom et s'engage contractuellement à prendre des mesures pour garantir la sécurité et la confidentialité des données traitées.</p><br>
                <p>Lors de votre visite sur le site, les données suivantes sont notamment enregistrées :</p><br>
                <ul>
                <li>Pages consultées</li>
                <li>votre comportement sur les pages (par exemple temps passé sur le site, clics, comportement de défilement)</li>
                <li>Votre localisation approximative (pays et ville)</li>
                <li>votre adresse IP (sous forme abrégée, de sorte qu'aucune identification claire n'est possible)</li>
                <li>Informations techniques telles que le navigateur, le fournisseur d'accès à Internet, le terminal et la résolution d'écran</li>
                <li>la source de votre visite (c.-à-d. le site web ou le support publicitaire par lequel vous êtes arrivé chez nous)</li>

                </ul>  
                <p>Les données personnelles telles que le nom, l'adresse ou les coordonnées ne sont jamais transmises à Google Analytics.</p>
                <p>Ces données sont transmises aux serveurs de Google aux États-Unis. Nous attirons votre attention sur le fait qu'en matière de protection des données, le niveau de protection aux États-Unis ne peut pas être garanti de la même manière qu'au sein de l'EU. </p>
                <p>Google Analytics enregistre des cookies dans votre navigateur web pour une durée de deux ans depuis votre dernière visite. Ces cookies contiennent un identifiant d'utilisateur généré de manière aléatoire, qui permet de vous reconnaître lors de vos prochaines visites sur le site.</p>
                <p>Les données enregistrées sont stockées avec l'ID utilisateur généré de manière aléatoire, ce qui permet d'évaluer des profils d'utilisateurs pseudonymes. Ces données liées à l'utilisateur sont automatiquement effacées au bout de 14 mois. Les autres données restent stockées sous forme agrégée pour une durée illimitée.</p>
                <p>Si vous n'êtes pas d'accord avec la saisie, vous pouvez la refuser en installant une seule fois <a target="_blank" href="https://tools.google.com/dlpage/gaoptout?hl=fr">un Browser-Add-ons pour la désactivation de Google Analytics</a> ou en refusant les cookies via notre Cookie-Consent-Banner.</p>
             </div>
        </div>
    </div>
</body>
</html>